version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/" # Location of your package.json
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 10